
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CL2~PC17
 */
public class heynow extends javax.swing.JFrame {

    /**
     * Creates new form heynow
     */
    public heynow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtopt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtquan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtfood = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtdrinks = new javax.swing.JTextField();
        txtprice1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtoptdrinks = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtquan1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        txtquan2 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu");

        jLabel2.setText("[1]Pork chop P25");

        jLabel3.setText("[2]Kanin P10");

        jLabel4.setText("[3]Chopsuey P50");

        jLabel5.setText("[4]Adobo P60");

        jLabel6.setText("[5]Bulalo P70");

        jLabel7.setText("Food:");

        jLabel8.setText("Quantity");

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtfood.setEnabled(false);

        txtprice.setEnabled(false);

        jLabel9.setText("The Ordertaker");

        jLabel10.setText("Drinks");

        jLabel11.setText("[1]Coca-cola P15");

        jLabel12.setText("[2]Royal P15");

        jLabel13.setText("[3]Mountain Dew P18");

        jLabel14.setText("[4]Sting P25");

        jLabel15.setText("[5]Water P10");

        jButton2.setText("Select");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtdrinks.setEnabled(false);

        txtprice1.setEnabled(false);

        jLabel16.setText("Drinks:");

        jButton3.setText("Enter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Enter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel17.setText("Quantity");

        jLabel18.setText("Cash:");

        jButton5.setText("Pay");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtquan2.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel5)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jButton1))
                                            .addComponent(txtopt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtfood, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtquan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel3)
                        .addGap(57, 57, 57)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel11)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtoptdrinks)
                                            .addComponent(txtdrinks)
                                            .addComponent(txtprice1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtquan1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(124, 124, 124))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(157, 157, 157))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(txtpay)
                            .addComponent(txtquan2))))
                .addGap(247, 247, 247))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtopt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtoptdrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtquan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtquan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtquan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int opt = Integer.parseInt(txtopt.getText());
        if(opt == 1) {
            JOptionPane.showMessageDialog(null, "Pork chop", "Menu", JOptionPane.INFORMATION_MESSAGE);
            txtfood.setText("Pork Chop");
            txtprice.setText("₱25");
        }
        else if(opt == 2) {
            JOptionPane.showMessageDialog(null, "Kanin", "Menu", JOptionPane.INFORMATION_MESSAGE);
            txtfood.setText("Kanin");
            txtprice.setText("₱10");
        }
        else if(opt == 3) {
            JOptionPane.showMessageDialog(null, "Chopsuey", "Menu", JOptionPane.INFORMATION_MESSAGE);
            txtfood.setText("Chopsuey");
            txtprice.setText("₱50");
        }
        else if(opt == 4) {
            JOptionPane.showMessageDialog(null, "Adobo", "Menu", JOptionPane.INFORMATION_MESSAGE);
            txtfood.setText("Adobo");
            txtprice.setText("₱60");
        }
        else if(opt == 5) {
            JOptionPane.showMessageDialog(null, "Bulalo", "Menu", JOptionPane.INFORMATION_MESSAGE);
            txtfood.setText("Bulalo");
            txtprice.setText("₱70");
        }
        else {
            JOptionPane.showMessageDialog(null, "Meron ba kahit ano?", "Menu", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int opt = Integer.parseInt(txtoptdrinks.getText());
        if(opt == 1) {
            JOptionPane.showMessageDialog(null, "Coca-cola", "Drinks", JOptionPane.INFORMATION_MESSAGE);
            txtdrinks.setText("Coca-Cola");
            txtprice1.setText("₱15");
        }
        else if(opt == 2) {
            JOptionPane.showMessageDialog(null, "Royal", "Menu", JOptionPane.INFORMATION_MESSAGE);
            txtdrinks.setText("Royal");
            txtprice1.setText("₱15");
        }
        else if(opt == 3) {
            JOptionPane.showMessageDialog(null, "Mountain Dew", "Menu", JOptionPane.INFORMATION_MESSAGE);
            txtdrinks.setText("Mountain Dew");
            txtprice1.setText("₱18");
        }
        else if(opt == 4) {
            JOptionPane.showMessageDialog(null, "Sting", "Menu", JOptionPane.INFORMATION_MESSAGE);
            txtdrinks.setText("Sting");
            txtprice1.setText("₱25");
        }
        else if(opt == 5) {
            JOptionPane.showMessageDialog(null, "Water", "Menu", JOptionPane.INFORMATION_MESSAGE);
            txtdrinks.setText("Water");
            txtprice1.setText("₱10");
        }
        else {
            JOptionPane.showMessageDialog(null, "Meron ba kahit ano?", "Menu", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int opt = Integer.parseInt(txtopt.getText());
        if(opt == 1) {
        int pork = 25;
        int quan = Integer.parseInt(txtquan.getText());
        int quan1 = pork * quan;
        JOptionPane.showMessageDialog(null, "Your total is:"+ quan1, "Receipt", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(opt == 2) {
            int kanin = 10;
            int quan = Integer.parseInt(txtquan.getText());
            int quan1 = kanin * quan;
            JOptionPane.showMessageDialog(null, "Your total is:"+ quan1, "Receipt", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(opt == 3) {
            int chopsuey = 50;
            int quan = Integer.parseInt(txtquan.getText());
            int quan1 = chopsuey * quan;
            JOptionPane.showMessageDialog(null, "Your total is:"+ quan1, "Receipt", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(opt == 4) {
            int adobo = 60;
            int quan = Integer.parseInt(txtquan.getText());
            int quan1 = adobo * quan;
            JOptionPane.showMessageDialog(null, "Your total is:"+ quan1, "Receipt", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(opt == 5) {
            int bulalo = 70;
            int quan = Integer.parseInt(txtquan.getText());
            int quan1 = bulalo * quan;
            JOptionPane.showMessageDialog(null, "Your total is:"+ quan1, "Receipt", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "WALA?!", "The UNordertaker", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int opt = Integer.parseInt(txtoptdrinks.getText());
        if(opt == 1) {
        int coke = 15;
        int quan = Integer.parseInt(txtquan.getText());
        int quan1 = coke * quan;
        JOptionPane.showMessageDialog(null, "Your total is:"+ quan1, "Receipt", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(opt == 2) {
            int royal = 15;
            int quan = Integer.parseInt(txtquan.getText());
            int quan1 = royal * quan;
            JOptionPane.showMessageDialog(null, "Your total is:"+ quan1, "Receipt", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(opt == 3) {
            int mountain = 18;
            int quan = Integer.parseInt(txtquan.getText());
            int quan1 = mountain * quan;
            JOptionPane.showMessageDialog(null, "Your total is:"+ quan1, "Receipt", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(opt == 4) {
            int sting = 25;
            int quan = Integer.parseInt(txtquan.getText());
            int quan1 = sting * quan;
            JOptionPane.showMessageDialog(null, "Your total is:"+ quan1, "Receipt", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(opt == 5) {
            int water = 10;
            int quan = Integer.parseInt(txtquan.getText());
            int quan1 = water * quan;
            JOptionPane.showMessageDialog(null, "Your total is:"+ quan1, "Receipt", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "WALA?!", "The UNordertaker", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int opt = Integer.parseInt(txtpay.getText());
        if(opt == 1) {
        int pork = 25;
        int quan = Integer.parseInt(txtpay.getText());
        int quan1 = pork * quan;
        int cash = Integer.parseInt(txtquan2.getText());
        int change = cash - quan1;
        JOptionPane.showMessageDialog(null, "Your change is:"+ change, "Price", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(opt == 2) {
        int kanin = 10;
        int quan = Integer.parseInt(txtpay.getText());
        int quan1 = kanin * quan;
        int cash = Integer.parseInt(txtquan2.getText());
        int change = cash - quan1;
        JOptionPane.showMessageDialog(null, "Your change is:"+ change, "Price", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(opt == 3) {
        int chopsuey = 50;
        int quan = Integer.parseInt(txtpay.getText());
        int quan1 = chopsuey * quan;
        int cash = Integer.parseInt(txtquan2.getText());
        int change = cash - quan1;
        JOptionPane.showMessageDialog(null, "Your change is:"+ change, "Price", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(opt == 4) {
        int adobo = 60;
        int quan = Integer.parseInt(txtpay.getText());
        int quan1 = adobo * quan;
        int cash = Integer.parseInt(txtquan2.getText());
        int change = cash - quan1;
        JOptionPane.showMessageDialog(null, "Your change is:"+ change, "Price", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(opt == 5) {
        int bulalo = 70;
        int quan = Integer.parseInt(txtpay.getText());
        int quan1 = bulalo * quan;
        int cash = Integer.parseInt(txtquan2.getText());
        int change = cash - quan1;
        JOptionPane.showMessageDialog(null, "Your change is:"+ change, "Price", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "WALA?!", "The UNordertaker", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(heynow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(heynow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(heynow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(heynow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new heynow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtdrinks;
    private javax.swing.JTextField txtfood;
    private javax.swing.JTextField txtopt;
    private javax.swing.JTextField txtoptdrinks;
    private javax.swing.JTextField txtpay;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtprice1;
    private javax.swing.JTextField txtquan;
    private javax.swing.JTextField txtquan1;
    private javax.swing.JTextField txtquan2;
    // End of variables declaration//GEN-END:variables
}
